name: Build and Publish to NPM

on:
  push:
    branches:
      - master   # only run when PRs are merged into master
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true npm ci

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Increment version
        id: version
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type || 'patch' }}"
          npm version $VERSION_TYPE --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          
          # Update the library's package.json version too
          node -e "
            const fs = require('fs');
            const libPkg = JSON.parse(fs.readFileSync('src/lib/package.json', 'utf8'));
            libPkg.version = '$NEW_VERSION';
            fs.writeFileSync('src/lib/package.json', JSON.stringify(libPkg, null, 2) + '\n');
          "
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version change
        run: |
          git add package.json package-lock.json src/lib/package.json
          git commit -m "chore: bump version to v${{ steps.version.outputs.new_version }}"
          git tag "v${{ steps.version.outputs.new_version }}"
          git push origin master --tags